### ISSUE TITLE
Is this because the versions don't match?

### ISSUE THREAD

**Issue by itxiaolin** [gotmc/libusb#20]
# github.com/gotmc/libusb
/data/gopath/pkg/mod/github.com/gotmc/libusb@v1.0.22/miscellaneous.go:34:38: cannot use int32(err) (value of type int32) as type _Ctype_int in argument to (_Cfunc_libusb_strerror)

**Comment by itxiaolin** [comment]
pkg-config --modversion libusb-1.0
1.0.24
pkg-config --cflags  -- libusb-1.0
-I/usr/include/libusb-1.0

**Comment by zhuewizz** [comment]
i meet the same problem too
pkg-config --modversion libusb-1.0
1.0.26
pkg-config --cflags -- libusb-1.0
-I/usr/include/libusb-1.0

**Comment by NullYing** [comment]
I meet the same problem too

**Comment by fouriier** [comment]
import as "github.com/gotmc/libusb/v2", that worked for me

**Comment by matthewrankin** [comment]
Yes, please import `github.com/gotmc/libusb/v2` as v1 is no longer supported.
