### ISSUE TITLE
Issue with getting the package

### ISSUE THREAD

**Issue by draganbobas** [gotmc/libusb#6]
Ran: go get github.com/gotmc/libusb
Expected: No issues 
Got: `# github.com/gotmc/libusb
../../workspace/src/github.com/gotmc/libusb/context.go: In function 'set_debug':
../../workspace/src/github.com/gotmc/libusb/context.go:11:34: error: 'LIBUSB_OPTION_LOG_LEVEL' undeclared (first use in this function); did you mean 'LIBUSB_ERROR_NO_MEM'?
 //   return libusb_set_option(ctx, LIBUSB_OPTION_LOG_LEVEL, level);
                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                  LIBUSB_ERROR_NO_MEM
../../workspace/src/github.com/gotmc/libusb/context.go:11:34: note: each undeclared identifier is reported only once for each function it appears in
`

**Comment by matthewrankin** [comment]
@draganbobas Sorry to hear that. Could you please provide a little more information?

1. What O/S are you running?
2. What version of the [libusb C library](https://libusb.info/) are you running?
3. What version of Go are you running?

**Comment by draganbobas** [comment]
@matthewrankin Sure 
1. `uname -a` 
Linux ubuntu 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

2. `dpkg -l | grep libusb`
ii  libgusb2:amd64                        0.2.11-1                                        amd64        GLib wrapper around libusb1
ii  libusb-0.1-4:amd64                    2:0.1.12-31                                     amd64        userspace USB programming library
ii  libusb-1.0-0:amd64                    2:1.0.21-2                                      amd64        userspace USB programming library
ii  libusb-1.0-0-dev:amd64                2:1.0.21-2                                      amd64        userspace USB programming library development files
ii  libusb-1.0-doc                        2:1.0.21-2                                      all          documentation for userspace USB programming
ii  libusbmuxd4:amd64                     1.1.0~git20171206.c724e70f-0.1                  amd64        USB multiplexor daemon for iPhone and iPod Touch devices - library
3. `go version`
go version go1.10.8 linux/amd64


Also I installed google's gousb before trying your package if it helps.

**Comment by matthewrankin** [comment]
It appears you're using libusb 1.0.21. There was a breaking change in libusb 1.0.22 related to `libusb_set_debug`, which was fixed in commit 558d53e. Is there any way you could install libusb 1.0.22 to see if this fixes the problem?

**Comment by matthewrankin** [comment]
I added a `v1.0.21` release to the last commit before fixing the v1.0.22 breaking change, so you could install `v1.0.21` to see if that resolves the problem.

**Comment by 404th** [comment]
What to do next if there is a problem with v1.0.21?
